### ISSUE TITLE
Translucent images result in a mess!

### ISSUE THREAD

**Issue by ThePicoNerd** [jaredforth/webp#2]
I want to start off by saying thank you for this awesome crate! It has really made my development a lot easier and above all safer. I'm currently building a media proxy in Rust to download an image and then send it back to the client, encoded in a specified format, and with set dimensions. When I tried doing this with the translucent image below, I got a weird output.
![Original image](https://user-images.githubusercontent.com/17624114/86497993-20180800-bd84-11ea-8a4b-175dbde6c1ab.png)
![WebP](https://user-images.githubusercontent.com/17624114/86498108-9b79b980-bd84-11ea-9523-bfd33e07d4ac.png)
(I was forced to convert the WebP image to PNG because GitHub wouldn't allow a WebP image to be uploaded, but it looks the same as the WebP).

A temporary fix right now is to convert the `DynImage` to a `RgbImage` before encoding it, and this just strips the alpha channel completely. I understand that implementing alpha channel support might be tricky, but could a temporary workaround be implemented? I'm certain that many would appreciate a non-transparent image above a glitched one :)

This is my workaround (please keep in mind that I am very new to Rust!):
```rust
fn webp(img: &DynamicImage, quality: f32) -> Result<Vec<u8>, image::ImageError> {
    let (width, height) = img.dimensions();
    let rgb = img.to_rgb();
    let encoded = webp::Encoder::from_rgb(&rgb, width, height).encode(quality);
    Ok(encoded.to_vec())
}
```

**Comment by jaredforth** [comment]
Hi @ThePicoNerd! 

Thanks for filing this issue! This crate is still very much in development so functionality is not stable and probably not production ready. If you feel comfortable making in a pull request with a fix I will review and merge quickly if it works. Otherwise, I will try and implement a fix as soon as I can.

**Comment by ThePicoNerd** [comment]
It seems like I was wrong all the time. Since the versions of the `image` crate were different in my application and this crate, I was forced to convert my `DynamicImage` to RGB and use the RGB encoder. I was stupid enough not to notice the RGBA encoder and just convert everything to RGBA.

I'm not at my computer right now, but I'll check later and if it works, I will close this issue.

Please excuse my stupidity!

**Comment by ThePicoNerd** [comment]
Can confirm it works perfectly well, just by switching to `webp::Encoder::from_rgba`.

**Comment by ThePicoNerd** [comment]
Maybe Dependabot could be enabled to keep all dependencies up-to-date?

**Comment by jaredforth** [comment]
@ThePicoNerd 

I'm glad you were able to get it figured out! I enabled Dependabot on the repo so dependencies should be updated going forward.
