### ISSUE TITLE
Upgrade image dependency to ^0.23.13

### ISSUE THREAD

**Issue by emirror-de** [jaredforth/webp#3]
Hey there,

do you have any plans upgrading the image dependency? I forked your repo and upgraded to 0.23.13. I needed to add a match condition to the new function in the Encoder struct, but then it compiles.
```rust
_ => {
  unreachable!()
}
```

I was not able to check it thoroughly. If you are interested to upgrade, I can create a pull request. I did not yet, because my IDE automatically called rustfmt on save with my preferences and I do not know what yours are.

[Link to forked commit](https://github.com/emirror-de/webp/commit/369063381f53096ad57b62f766dbac2596ee214e)

Greetings,
Lewin

**Comment by jaredforth** [comment]
@emirror-de Thanks for helping improve this crate! I updated the `image` dependency and made necessary changes in the code in https://github.com/jaredforth/webp/commit/41c66c960d4ffcca04bb05b941c00181646ea6c5. Let me know if you have any additional issues. 

Thanks, 

Jared
