### ISSUE TITLE
as_image naming incosistency

### ISSUE THREAD

**Issue by jwiesler** [jaredforth/webp#6]
`WebPImage::as_image` should be called `to_image` to reflect what it does. It does not take any references and is not a cheap conversion because it copies data.

**Comment by jaredforth** [comment]
I'm not sure if changing the public API of the crate is worth the naming convention change. Do you think mentioning the cost of the operation in the inline documentation is sufficient? 

I do see where you are coming from though. To be consistent with standard library functions such as `as_str()` and `to_string()` the `to_image()` is preferable.

**Comment by jaredforth** [comment]
I agree given that the crate is not on 1.0.0 and is depended on by only a handful of other crates. I'll make the change.
