### ISSUE TITLE
Replace unreachable! statements by returning Result<Self>

### ISSUE THREAD

**Issue by emirror-de** [jaredforth/webp#8]
This somehow relates to #7, but seems different enough to me to create a new issue for this.

I am using your crate in my [html5-picture](https://github.com/emirror-de/html5-picture). Since `webp` calls `unreacheable!` when a color profile is not supported, I am required to use `panic::catch_unwind` to be able to skip unsupported color profiles.

To prevent me from checking for supported color profiles and synchronize my crate every time `webp` changes and gets new implementations, it would be awesome that the `from_XXX` functions return `Result<Self>` instead of `Self`. This way it would be possible to skip unsupported profiles without catching a panic resulting in cleaner code.

**Comment by jaredforth** [comment]
This is a good idea. I started implementation for the `Encoder` struct here: https://github.com/jaredforth/webp/commit/25eb15518cf1aab90be6ade47ff9aa482a099c6a

**Comment by jaredforth** [comment]
This is implemented for `webp = "0.2.0"` version

**Comment by emirror-de** [comment]
Hell, that was fast! Great work, thank you!
